import 'dart:io';

import 'package:flutter/material.dart';

// To get started quickly, change this to your heroku deployment of
// https://github.com/PaystackHQ/sample-charge-card-backend
// Step 1. Visit https://github.com/PaystackHQ/sample-charge-card-backend
// Step 2. Click "Deploy to heroku"
// Step 3. Login with your heroku credentials or create a free heroku account
// Step 4. Provide your secret key and an email with which to start all test transactions
// Step 5. Replace {YOUR_BACKEND_URL} below with the url generated by heroku (format https://some-url.herokuapp.com)
// Set this to a public key that matches the secret key you supplied while creating the heroku instance

// String backendUrl = '{YOUR_BACKEND_URL}';
String paystackPublicKey = "pk_live_bcddf6973cdcbd5811ae519ab726adb9cce4091f";
const String appName = 'everyday.org';

var banks = ['Selectable', 'Bank', 'Card'];

const Color green = Color(0xFF3db76d);
const Color lightBlue = Color(0xFF34a5db);
const Color navyBlue = Color(0xFF031b33);

const verticalSizeBox = SizedBox(height: 20.0);
const horizontalSizeBox = SizedBox(width: 10.0);
final border = Container(
  width: double.infinity,
  height: 1.0,
  color: Colors.red,
);

String getReference() {
  String platform;
  if (Platform.isIOS) {
    platform = 'iOS';
  } else {
    platform = 'Android';
  }

  return 'ChargedFrom${platform}_${DateTime.now().millisecondsSinceEpoch}';
}
